#!/bin/sh

# Supersplice - apply a sed-style regular expression against a set of files
#
# Copyright (C) 2000-2024, David Charlap
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <https://www.gnu.org/licenses/>.

# usage: supersplice <regex> file [file...]

if ( [ -z $2'' ];) then
    echo 'usage: supersplice <regex> file [file...]'
    exit
fi

tempfile=/tmp/supersplice.temp.$$

regex=$1
shift 1

for i in $*; do
    if ( sed "$regex" $i > $tempfile; ) then 
	cp $tempfile $i
	rm $tempfile
    fi
done
